### ISSUE TITLE
AnsiColoringRichTextBox parsing

### ISSUE THREAD

**Issue by wvdvegt** [Mortens4444/Mtf.Controls#1]
Your AnsiColoringRichTextBox class seems a nice candidate for replacing my aging (and a.t.m. troublesome) console based solution. Besides some minor issues I'm quite surprised by speed and lack of flickering.

But during porting my code to use your control i notices some issues:

- There seems to be an issue in the ANSI code parsing regarding modifiers.

In the sequence ESC[1;30m the 1 stands for bold and the 30 for the color (black).

So it's best to capture the 1;30 part and split it on the semicolon so it can be applied to the font easier (than a large lookup table) Now it's impossible to issue a bold sequence ESC[1m or reset ESC[0m on the current color. The same holds for the other font modifiers

See: https://gist.github.com/ConnerWill/d4b6c776b509add763e17f9f113fd25b

- The order of the individual items inside the ESC[m does also not matter. So ESC[1;31m is equivalent with ESC[31;1m.
- The 'ansiColorMap' dictionary seems to be duplicated as 'dictionary'. 
- There is no reverse table (color->escape sequence).
- The dependencies for the nuget package are a bit off-scale with AForce and Accord if i just want to use only the AnsiColoringRichTextBox control.

**Comment by Mortens4444** [comment]
Dear wvdvegt,

Thank you for reporting the issues in the previous version. I’ve addressed the problems and released an updated version.
I’d appreciate it if you could give it another try and let me know if everything works as expected now.

Best regards,
Mortens

PS.: You mentioned that there is no reverse table (color->escape sequence), could you please clarify why is it important and how would you use it?

**Comment by wvdvegt** [comment]
**> PS.: You mentioned that there is no reverse table (color->escape sequence), could you please clarify why is it important and how would you use it?**

I use the lookup to add some helper methods that my program uses to set for instance the background color to black (and text color to white) without having to know ANSI codes.

I use the ANSI console as control on a component derived from a (win)form. I would like to keep all ANSI code in that control.

The app I'm updating uses a Arduino alike board and renders it's output on the console (but the app may do some additional parsing and insert some coloring (or make some text bold) based on the text it receives and appends to the control. 

The text typed in the control (including arrow keys) is sent to the device (which then generates output that is caught by the program, processed & enhanced a bit and sent to the console for rendering.

Instead of a separate lookup dictionary I could probably have used link to match values and retrieve the key from the ansiColorMap.

**Comment by wvdvegt** [comment]
Had a look at the code and it looks much cleaner. 

I'll try to add my cursor movement code and support for line and screen clearing as well.

**Comment by Mortens4444** [comment]
I created a function with the following syntax:
public void AppendText(string text, params AnsiColoringMode[] ansiColoringModes)

I’d be happy if you could try using it.
You can find an example of how to use it in Mtf.Controls.Test.

**Comment by Mortens4444** [comment]
I believe all your concerns have been addressed. If there's anything still outstanding, please let me know. Otherwise, I will proceed to close the ticket.

**Comment by wvdvegt** [comment]
Things seem a bit broken around line endings.

When i add a character at a time I get \r or \n inserted. If in my tool i type a 'cls' command it looks like

![Image](https://github.com/user-attachments/assets/c6d01409-f463-4f30-be28-71041f1f0b97)

In above screenshot the lower case is what is typed in the control and the uppercase is what I get in my wrapper and send to the device. Ideally I would like to see only what i send/receive to/from the device attached. Found i missed setting some e.Handled properties of the keypress/down events.

Something similar happened (in the previous version) when i try to add a piece of text with line-endings in it (BUT not at the end). Instead of a cursor behind the prompt, i got an extra line.

![Image](https://github.com/user-attachments/assets/0dd363fa-4049-41e9-9cbb-1f0a0a1a882a)

In the latest version (see above) it's two extra lines. The caret should end up after the '>' character in CMD>.

It seems to originate from splitting the text in lines (and end up with lines that have a trailing \r.

**Comment by wvdvegt** [comment]
Found a solution for my coding: set e.SuppressKeyPress = true; in the KeyDown event to true.

See https://stackoverflow.com/questions/4683663/how-to-remove-annoying-beep-with-richtextbox

**Comment by Mortens4444** [comment]
If you're still having trouble, feel free to share a snippet of your code. It sounds like you're on the right track though.

**Comment by wvdvegt** [comment]
Hi, Things start to look good, but i had to change some code to get rid of a fixed CRLF at the end of text (my console component displays a prompt line CMD> and there should be no trailing CRLF.

So i changed AppendText(string text) to: 

```
public new void AppendText(string text)
{
    if (String.IsNullOrEmpty(text))
    {
        return;
    }

    var lines = text.Split(separator, StringSplitOptions.RemoveEmptyEntries);
    if (lines.Length > 1)
    {
        foreach (var line in lines.Take(lines.Length - 1))
        {
            AppendTextPart(line);
            base.AppendText(Environment.NewLine);
        }
    }
    if (lines.Length > 0 && lines.Last().Length > 0)
    {
        AppendTextPart(lines.Last());
    }
    if (text.Length > 0 && separator.Contains(text.Last()))
    {
        base.AppendText(Environment.NewLine);
    }
}
```

**Comment by Mortens4444** [comment]
What about if we remove the newline splitting completely? I created a fix to this, you can check out the new code, or update the Mtf.Controls package from api.nuget.org also. Please let me know if it solves your problem.

**Comment by wvdvegt** [comment]
Did a quick check and it seems to work just fine.

I still do have a scrolling issue i will investigate and try to incorporate my support for some more (clear line/screen & cursor escape codes).

Finally the code below looks like an error in the attribute

```
    [ToolboxBitmap(typeof(SourceCodeViewerRichTextBox), "Resources.SourceCodeViewerRichTextBox.png")]
    public class AnsiColoringRichTextBox : RichTextBox
```
Should SourceCodeViewerRichTextBox (and the png not be AnsiColoringRichTextBox ?

so

`[ToolboxBitmap(typeof(AnsiColoringRichTextBox), "Resources.AnsiColoringRichTextBox.png")]`

**Comment by Mortens4444** [comment]
Thank you for letting me know about the bugs. You can check the updated source code for moving the caret.

**Comment by wvdvegt** [comment]
I tried to compile it but I get an error about nuGet packages references:

Unable to find package Mtf.Network with version (>= 2.0.3)
  - Found 33 version(s) in nuget.org [ Nearest version: 2.0.0 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in C:\Program Files\dotnet\library-packs
  - Found 0 version(s) in Local

I have no clue why this Network packages is being pulled in suddenly.

**Comment by wvdvegt** [comment]
Small issue:

Although it sees like these lines set the control back and font color (it shows correctly after startup):

```
            AnsiRichText.DefaultBackColor = AnsiRichText.BlackColor;
            AnsiRichText.DefaultFontColor = AnsiRichText.WhiteColor;

```
But don't seem the initial starting colors for processing and sending ANSI Coloring codes. Without the following line  coloring reverts back to assuming a black text again (making text invisible in my black background console):

![Image](https://github.com/user-attachments/assets/7b2e1fed-ce1d-4ea2-aaf4-36e525f5656b)

`            AnsiRichText.AppendText($"{Ansi.ESC}[30;40m");`

With the extra line things look better/correct:

![Image](https://github.com/user-attachments/assets/9dddb055-37ed-43d6-919a-986054b7db4f)

**Comment by wvdvegt** [comment]
Another possible issue:

When i type a character and append it to the console I try to scroll it into view with

```
            AnsiRichText.SelectionStart = AnsiRichText.TextLength;
            AnsiRichText.ScrollToCaret();
```
The first like correcly scrolls the window (text is nicely visible). 
However the ScrollToCaret() call scrolls it down about half a line making it hard to read.

I'm still investigating where this issue originates.

**Comment by wvdvegt** [comment]
Another issue:

It seems like the Lines property isn't working anymore (I use it to prune text from the console (to limit the scroll-back buffer). The code:

`     public string[] Lines => Text.Split(new string[] { Environment.NewLine }, StringSplitOptions.None);`

Seems to split Text (with \n\n line endings with Environment.NewLine (\r\n) resulting in a always 1 return value.

I'm investigating from here the \n\n originates.

Btw using Environment.NewLine is dangerous (imho) as it can change between machines. Maybe better to use a property for it with Environment.NewLine as default (so one can override it when needed).

**Comment by Mortens4444** [comment]
I pushed some changes based on your concerns. Mtf.Network is used by Mtf.Controls.Video, but you can safely remove it from the solution — it won't cause any issues. Anyway, I’ve uploaded the missing 2.0.3 package for it.
I also tried to fix the control’s background and font color issue, and added two new properties to properly handle the Lines property (StringSplitOptions and LineSeparators).
As for the scrolling issue, I’m still struggling with it and not sure how to solve it yet."

**Comment by wvdvegt** [comment]
The main issue with Mtf.Controls.Video, was that it pulled in 3rd party NuGet packages that where not uninstalled on Mtf.Controls.Video's removal. 

At the moment i just use a copied set of the source files need to compile the control.

As for the scrolling, i think it might be something as one method scrolls to the end of the scrollbar and the other to a line in the control.

For my private Clear Screen (ESC[*J )  and Line Deletions (ESC[*K) I rewrote my own splitting code into 3 parts and use some recursion. If nothing matches, text is sends to the AnsiColoringRichTextBox's AppendText without further processing. Btw I do this in my ow AppendText method. 

1) The left part is the plain text up to the first regex match, which can be send to AppendText to the AnsiColoringRichTextBox without further processing.
2) I perform the screen clearing or line deletion depending on the match.
3) The remaining (right) part I just send recursively to my own AppenText method where it either gets matched and split into 3 again or (if no further ansi sequences are matched, directly to AnsiColoringRichTextBox's AppendText.

The code:

```
 private void AppendText(string text)
 {
     if (Ansi.BackSpace.IsMatch(text))
     {
         Match m = Ansi.Ansi_J.Match(text);

         string left = text.Substring(0, m.Index);
         // string esc = text.Substring(m.Index, m.Length);
         string right = text.Substring(m.Index + m.Length);

         //! Left part
         if (!string.IsNullOrEmpty(left))
         {
             AppendText(left);
         }

         //! Handle BACKSPACE
         // 
         AnsiRichText.SelectionStart = AnsiRichText.TextLength;
         if (AnsiRichText.SelectionStart > 0)
         {
             AnsiRichText.Select(AnsiRichText.SelectionStart - 1, 1);
             AnsiRichText.Cut();
             AnsiRichText.Update();
         }

         //! Right part
         if (!string.IsNullOrEmpty(left))
         {
             AppendText(right);
         }
     }
     else if (Ansi.Bell.IsMatch(text))
     {
         Match m = Ansi.Ansi_J.Match(text);

         string left = text.Substring(0, m.Index);
         // string esc = text.Substring(m.Index, m.Length);
         string right = text.Substring(m.Index + m.Length);

         //! Left part
         if (!string.IsNullOrEmpty(left))
         {
             AppendText(left);
         }

         //! Handle BELL
         Beep();

         //! Right part
         if (!string.IsNullOrEmpty(left))
         {
             AppendText(right);
         }
     }
     else if (Ansi.Ansi_J.IsMatch(text))
     {
         Match m = Ansi.Ansi_J.Match(text);

         string left = text.Substring(0, m.Index);
         // string esc = text.Substring(m.Index, m.Length);
         string right = text.Substring(m.Index + m.Length);

         //! Left part
         if (!string.IsNullOrEmpty(left))
         {
             AppendText(left);
         }
         //! ESC[nJ (Screen Clearing Operations)
         if (m.Groups.Count == 2)
         {
             switch (m.Groups[1].Value)
             {
                 case "":
                 case "0":
                     //! erase in display(same as ESC[0J)
                     ClearScreen_CursorToEnd();
                     break;
                 case "1":
                     //! erase from cursor to beginning of screen
                     ClearScreen_BeginToCursor();
                     break;
                 case "2":
                     //! erase entire screen
                     ClearScreen();
                     break;
                 case "3":
                     //! erase saved lines?
                     break;
             }
         }

         //! Right part
         if (!string.IsNullOrEmpty(left))
         {
             AppendText(right);
         }
     }
     else if (Ansi.Ansi_K.IsMatch(text))
     {
         Match m = Ansi.Ansi_K.Match(text);

         string left = text.Substring(0, m.Index);
         // string esc = text.Substring(m.Index, m.Length);
         string right = text.Substring(m.Index + m.Length);

         //! Left part
         if (!string.IsNullOrEmpty(left))
         {
             AppendText(left);
         }

         //! ESC[nK (Line Clearing Operations)
         if (m.Groups.Count == 2)
         {
             switch (m.Groups[1].Value)
             {
                 case "":
                 case "0":
                     //! erase in line(same as ESC[0K)
                     DeleteLine_CursorToEndOfLine();
                     break;
                 case "1":
                     //! erase start of line to the cursor
                     DeleteLine_CursorToBeginOfLine();
                     break;
                 case "2":
                     //! erase the entire line
                     DeleteLine();
                     break;
             }
         }

         //! Right part
         if (!string.IsNullOrEmpty(right))
         {
             AppendText(right);
         }
     }
     else
     {
         AnsiRichText.AppendText(text);
     }
     AnsiRichText.Update();

     //! Prune # of Lines.
     //
     if (AnsiConsoleSettings.History > 0)
     {
         timer1.Stop();
         if (Lines() > AnsiConsoleSettings.History + AnsiConsoleSettings.HistoryThreshold)
         {
             bool ro = AnsiRichText.ReadOnly;
             AnsiRichText.ReadOnly = false;
             AnsiRichText.KeepMaxLines(AnsiConsoleSettings.History);
             AnsiRichText.ReadOnly = true;
         }
         timer1.Start();
     }

     AnsiRichText.SelectionStart = AnsiRichText.TextLength;
     //AnsiRichText.ScrollToCaret();
 }
```

and

```
public static class Ansi
{
    #region Fields

    /// <summary>
    /// (Immutable) The bell.
    /// </summary>
    public const string BELL = "\x7";

    /// <summary>
    /// (Immutable) The bs.
    /// </summary>
    public const string BS = "\x8";

    /// <summary>
    /// (Immutable) The escape.
    /// </summary>
    public const string ESC = "\x1B";

    public static readonly Regex Prompt = new Regex(@"([a-z;A-Z]+)>$");

    public static readonly Regex Bell = new Regex("([\x7])");
    public static readonly Regex BackSpace = new Regex("([\x8])");

    public static readonly Regex Ansi_J = new Regex(ESC + @"\[([0-3]?)J");
    public static readonly string ClearFromCursorToEnd = ESC + @"[0J";
    public static readonly string ClearFromStartToCursor = ESC + @"[1J";
    public static readonly string ClearScreen = ESC + @"[2J";

    /// <summary>
    /// (Immutable) The colour source.
    /// </summary>
    public static readonly Regex Ansi_K = new Regex(ESC + @"\[([0-2]?)K");
    public static readonly string DeleteLine = ESC + @"[2K";
    public static readonly string DeleteToEndOfLine = ESC + @"[0K";
    public static readonly string DelFromStartOfLine = ESC + @"[1K";

    #endregion Fields
}
```

**Comment by Mortens4444** [comment]
I've implemented some of the control and erase commands in the latest commit. You can check it out if you'd like. But feel free to create your own version if mine doesn't suit your needs.

**Comment by wvdvegt** [comment]
As far as i could test at the moment the line/screen clearing works, but i see some irregularities in delete to end of line (will run it in the debugger to set a breakpoint and see the selected text to cut). On some lines it works on others it fails and leaves some text.

Example:
`        Echo byte                       - Echo On|Off (1|0) (global command),`
leaves
`        Echo byte                       - 0) (global command),`

I send a ESC + @"[0K"

![Image](https://github.com/user-attachments/assets/921c5fb6-c7a7-4070-a6c9-f20959abe4ae)

The screenshot shows your EraseFromCursorToEndOfLine() select to much 
`"Echo On|Off (1|0) (global command),\n        " `
instead of:
`"Echo On|Off (1|0) (global command)," `

**Comment by wvdvegt** [comment]
I did some debugging and it seems the Lines array is not in sync with the GetLineFromCharIndex/GetFirstCharIndexFromLine.

The beginning of lines and the offset to the caret are ok, it's the charsToErase that is wrong somehow.

It's seems the lineindex or Lines is not ok (I just noticed that inside EraseFromCursorToEndOfLine() it's 3 lines of (Lines[lieIndex-3] shows the line i used for testing)

**Comment by Mortens4444** [comment]
Hello, I pushed a fix for the erase line problem, you can check it.

**Comment by wvdvegt** [comment]
The fix still failed (My assumption is that under the hood it end up in the TextBoxBase class which probably only sees the RTF as it's text.

The following line based code works (the -1 is for the line separator so i'm not 100% sure it's always -1.

When out of range, the Get* methods seem to return -1.

```
public void EraseFromCursorToEndOfLine()
{
    var lineIndex = GetLineFromCharIndex(SelectionStart);
    var lineStart = GetFirstCharIndexFromLine(lineIndex);
    var lineEnd = GetFirstCharIndexFromLine(lineIndex + 1) - 1;
            if (lineEnd < 0)
            {
                lineEnd = Text.Length;
            }
    var lineLength = lineEnd - lineStart;
    var cursorOffset = SelectionStart - lineStart;
    
    var charsToErase = lineLength - cursorOffset;

    if (charsToErase > 0)
    {
        Select(SelectionStart, charsToErase);
        SelectedText = String.Empty;
    }
}
```
[edit1] works was a bit to early, it has issues with the last line. I updated the code but it needs further testing of edge cases.

[edit2]
I adjusted the code again a bit (it now used Text.Length which seems to return the correct value i need). GetLineLength() didn't somehow.

Btw In the VS watch window I see:

`((RichTextBox)this).Lines.Count()`
and 
`Line.Count() `
return different values.

However my adjusted code did the right thing. Have you used the 'new' keyword to replace existing properties?

**Comment by Mortens4444** [comment]
No, I didn't use the new keyword. But I made two readonly properties writable, so I could change the StringSplitOptions to StringSplitOptions.None. That way, I got the same result for the line count.

**Comment by wvdvegt** [comment]
After some issues in my code (stringsplit options value was not applied properly), it works like charm!

I also added a (simple) dark mode (mainly the following code (call it before the control shows)):

```
 AnsiRichText.DefaultBackgroundColor = AnsiConsoleSettings.DarkTheme ? AnsiRichText.BlackColor : AnsiRichText.WhiteColor;
 AnsiRichText.DefaultFontColor = AnsiConsoleSettings.DarkTheme ? AnsiRichText.WhiteColor : AnsiRichText.BlackColor;

 AnsiRichText.BackColor = AnsiRichText.DefaultBackgroundColor;
 AnsiRichText.ForeColor = AnsiRichText.DefaultFontColor;

                AnsiRichText.AppendText(AnsiRichText.ColorToAnsi(
                    AnsiConsoleSettings.DarkTheme
                       ? Color.White
                       : Color.Black,
                    AnsiConsoleSettings.DarkTheme
                       ? Color.Black
                       : Color.White));
```
and two extension methods:
```
public static string ColorToAnsi(this AnsiColoringRichTextBox control, Color color, bool backColor = false)
{
        return string.Format($"{Ansi.ESC}[{(int)control.ColorToAnsiColoringMode(color, backColor)}m");
}
public static string ColorToAnsi(this AnsiColoringRichTextBox control, Color foreColor, Color backColor)
{
            return string.Format($"{Ansi.ESC}[{(int)control.ColorToAnsiColoringMode(foreColor)};{(int)control.ColorToAnsiColoringMode(backColor, true)}m");
}
```

It needs some extra work for being able to convert to ANSI and use the two default colors and add an accent color.

**Comment by Mortens4444** [comment]
I added a Theme parameter to the constructor, I hope it will be enough. Thank you very much for your contribution – I really appreciate your help and the time you’ve dedicated to this!
Just to confirm, is it okay to close this ticket now, or is there anything else that still needs to be addressed?

**Comment by wvdvegt** [comment]
Think this ticket/issue can be closed safely. I'll create a new one when I run into something new. 

For now it works just fine (have to checkout the Theme parameter). So many thanks for your efforts extending this control.

I like to help people coding and improving controls and libraries (so I have no problem dedicating some time, it was worth it).

Besides it also solved a pretty nasty issue with the native Console Windows && API when running under a debugger that cost me a lotta time without much progress.
